### ISSUE TITLE
4-channel image

### ISSUE THREAD

**Issue by chamovdmitrij** [Peterande/D-FINE#30]
@Peterande 
Thank you for your model. I will carefully compare it with the results of YOLO 11 on the dataset in my work project. 

I will ask you a question in advance, the answer to which I did not immediately find in the ultralyrics community in their issues. 
What changes and where in your code should I make to train a model that receives an image with 4 channels as input?
As the 4th channel, I am sending an image with a depth map, which I receive using the Depth Pro model. 
I expect that this will allow for better recognition of objects in the image due to more information. 

Thank you for your help!!!

**Comment by Peterande** [comment]
https://github.com/Peterande/D-FINE/blob/7240fb16ddd072bc591511bee17c84922aaf50b3/src/nn/backbone/hgnetv2.py#L356-L434

You should modify the first number of "stem_channels" here, changing it from 3 to 4. However, since DETR needs to load the pre-trained backbone weights, you need to make modifications to the weight parameters. There is also another idea. Without changing the current model, you can add an additional stem layer with an input of 4 channels (RGBD) or 1 channel (D) separately at the very beginning of hgnetv2 backbone, and then fuse the feature maps extracted by this additional layer with the original ones.
