### ISSUE TITLE
HGNetv2 latency

### ISSUE THREAD

**Issue by ShihuaHuang95** [Peterande/D-FINE#6]
Hi guys, it is a wonderful work. 
Regarding the latency, I have two confusions:
  1) When paired with HGNetv2-L and HGNetv2-X, the RT-DETRs achieve 114 and 74 FPS, respectively. However, the latency of RT-DETR with HGNetv2-L is 9.25 ms in your paper, which is about 108 FPS. Such a gap is unusual, as both of you claim to be on the same GPU device with TensorRT. Could you please explain it?  

Model | Input shape | Dataset | APval | AP50val | Params(M) | FLOPs(G) | T4 TensorRT FP16(FPS)
-- | -- | -- | -- | -- | -- | -- | --
RT-DETR-HGNetv2-L | 640 | COCO | 53.0 | 71.6 | 32 | 110 | 114
-- | -- | -- | -- | -- | -- | -- | --
RT-DETR-HGNetv2-X | 640 | COCO | 54.8 | 73.1 | 67 | 234 | 74

  2) In your ablation study, the latency drops from 9.25ms to 8.02ms after removing the decoder projection layers. As we know, the decoder projection layers in RT-DETR are a layer of Conv1x1 with BN. It is abnormal to save such costs after removing them. Could you please check this again?

**Comment by Peterande** [comment]
Thank you for your valuable questions!

1. Since it’s not the same machine, variables like CPU and hard drive performance can't be controlled, so I cannot reproduce the exact FPS from the original paper 100%. In fact, when testing across 8 independent T4 machines (both platform and local), a 0.5ms difference is quite normal, and this doesn't affect the relative speed between models. Please also refer to the papers of YOLOv10 and LW-DETR to check the differences in RT-DETR speed compared to the original paper.

2. Please check [this link](https://github.com/Peterande/D-FINE/blob/b27b1d8e596b83d98604958eba96761c027e7f54/src/zoo/dfine/dfine_decoder.py#L344). Removing the projection layer does not just save the time for Conv1x1; it also reduces many repeated memory accesses and processing operations.

**Comment by Peterande** [comment]
We removed not only the `input_proj` layer but also the `value_proj` and `output_proj` layers. This further reduces the computational complexity and memory access operations.
